In [1]:
import numpy as np


In [2]:
x1=np.array(55)
print(x1)
print(type(x1))


55
<class 'numpy.ndarray'>


In [3]:
x2=np.array([1,2,3,4,5,6,7,8])
print(x2)
print(type(x1))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.26.4


In [6]:
x3=np.array([[1,2,3],[4,5,6]])
print(x3)
print(type(x3))
print(x3.ndim)
print(x3.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)


In [8]:
x4=np.array([[1,2,3,4],[4,5,6,7],[8,9,5,3],[3,2,7,8]])
print(x4)
print(type(x4))
print(x4.ndim)
print(x4.shape)

[[1 2 3 4]
 [4 5 6 7]
 [8 9 5 3]
 [3 2 7 8]]
<class 'numpy.ndarray'>
2
(4, 4)


In [9]:
x5=np.array([[[2,4],[3,5]],[[6,8],[7,9]]])
print(x5)
print(type(x5))
print(x5.ndim)
print(x5.shape)

[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]
<class 'numpy.ndarray'>
3
(2, 2, 2)


In [10]:
x5=np.array([[[2,4],[3,5]],[[6,8],[7,9]],[[2,4],[3,5]],[[6,8],[7,9]]])
print(x5)
print(type(x5))
print(x5.ndim)
print(x5.shape)

[[[2 4]
  [3 5]]

 [[6 8]
  [7 9]]

 [[2 4]
  [3 5]]

 [[6 8]
  [7 9]]]
<class 'numpy.ndarray'>
3
(4, 2, 2)


#### Reshaping of an Arry

In [13]:
x6=np.array([1,2,3,4,5,6,7,8])
print(x6)
print(x6.ndim)
print(x6.shape)
print("*"*30)
x7=x6.reshape(4,2)
print(x7)
print(x7.ndim)
print(x7.shape)
print("*"*30)

[1 2 3 4 5 6 7 8]
1
(8,)
******************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2
(4, 2)
******************************


In [18]:
x8=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x8)
print(x8.ndim)
print(x8.shape)
print("*"*30)
x9=x8.reshape(4,3)
print(x9)
print(x9.ndim)
print(x9.shape)
print("*"*30)
x9=x8.reshape(4,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
******************************


In [21]:
x10=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x10)
print(x10.ndim)
print(x10.shape)
print("*"*30)
x11=x10.reshape(2,3,2)
print(x11)
print(x11.ndim)
print(x11.shape)
print("*"*30)
x11=x10.reshape(1,6,2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)
******************************


In [24]:
x10=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x10)
print(x10.ndim)
print(x10.shape)
print("*"*30)
x11=x10.reshape(6,2,1)
print(x11)
print(x11.ndim)
print(x11.shape)
print("*"*30)
x12=x10.reshape(1,6,2)
print(x12)
print(x12.ndim)
print(x12.shape)
print("*"*30)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]]
3
(6, 2, 1)
******************************
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
3
(1, 6, 2)
******************************


In [25]:
x13=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x13)
print(x13.ndim)
print(x13.shape)
print("*"*30)
x14=x13.reshape(2,3,2,1)
print(x14)
print(x14.ndim)
print(x14.shape)
print("*"*30)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]]
4
(2, 3, 2, 1)
******************************


In [26]:
x15=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x15)
print(x15.ndim)
print(x15.shape)
print("*"*30)
x16=x15.reshape(2,3,2,1,1)
print(x16)
print(x16.ndim)
print(x16.shape)
print("*"*30)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
******************************
[[[[[ 1]]

   [[ 2]]]


  [[[ 3]]

   [[ 4]]]


  [[[ 5]]

   [[ 6]]]]



 [[[[ 7]]

   [[ 8]]]


  [[[ 9]]

   [[10]]]


  [[[11]]

   [[12]]]]]
5
(2, 3, 2, 1, 1)
******************************


In [33]:
A=np.array([[4,3],[-5,9]])
b=np.array([20,96])
sol=np.linalg.solve(A,b)
print(sol)

[-2.11764706  9.49019608]


In [37]:
S=np.array([[12,14,-10],[-20,-15,12],[15,-4,5]])
F=np.array([20,21,12])
sol=np.linalg.solve(S,F)
print(sol)

[-1.74725275 19.56410256 23.29304029]


## Use Case Of Numpy for Image

In [42]:
from matplotlib.image import imread
hi=imread("C://Users//samru//OneDrive//Documents//Pictures//img1.jpg")
hi

array([[[159, 240, 122],
        [159, 240, 122],
        [159, 240, 122],
        ...,
        [159, 240, 122],
        [159, 240, 122],
        [160, 239, 122]],

       [[159, 240, 122],
        [159, 240, 122],
        [159, 240, 122],
        ...,
        [159, 240, 122],
        [159, 240, 122],
        [160, 239, 122]],

       [[159, 240, 122],
        [159, 240, 122],
        [159, 240, 122],
        ...,
        [159, 240, 122],
        [159, 240, 122],
        [160, 239, 122]],

       ...,

       [[159, 240, 122],
        [159, 240, 122],
        [159, 240, 122],
        ...,
        [159, 240, 122],
        [159, 240, 122],
        [160, 239, 122]],

       [[159, 240, 122],
        [159, 240, 122],
        [159, 240, 122],
        ...,
        [159, 240, 122],
        [159, 240, 122],
        [160, 239, 122]],

       [[161, 240, 123],
        [161, 240, 123],
        [161, 240, 123],
        ...,
        [161, 240, 123],
        [161, 240, 123],
        [161, 240, 123]]

In [43]:
from matplotlib.image import imread
hi2=imread("C://Users//samru//OneDrive//Documents//Pictures//jpgimg.jpg")
print(hi2)
print(hi2.ndim)
print(hi2.shape)

[[[252 255 255]
  [254 255 255]
  [254 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 255 255]
  [254 255 255]
  [254 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[252 255 255]
  [254 255 255]
  [254 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[251 255 254]
  [253 255 254]
  [253 255 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[251 255 254]
  [253 255 254]
  [253 255 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[251 255 254]
  [253 255 254]
  [253 255 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
3
(360, 643, 3)


### Matrix Solving

In [49]:
mat=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(mat)
print("___________________________________________________")
print(np.linalg.matrix_rank(mat))
print("___________________________________________________")
print(np.trace(mat))
print("___________________________________________________")
print(np.linalg.det(mat))
print("___________________________________________________")
print(np.linalg.inv(mat))

[[1 2 3]
 [4 5 6]
 [5 6 7]]
___________________________________________________
2
___________________________________________________
13
___________________________________________________
8.437694987151141e-16
___________________________________________________
[[-1.18515780e+15  4.74063119e+15 -3.55547339e+15]
 [ 2.37031559e+15 -9.48126237e+15  7.11094678e+15]
 [-1.18515780e+15  4.74063119e+15 -3.55547339e+15]]


In [51]:
np.linalg.matrix_power(mat,3)

array([[ 324,  414,  504],
       [ 750,  957, 1164],
       [ 892, 1138, 1384]])

In [54]:
mat2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat2)
c,d=np.linalg.eigh(mat2)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[-3.15746784 -0.67276795 18.8302358 ]
[[-0.80238891  0.43402538 -0.40962667]
 [-0.16812656 -0.82296167 -0.54264865]
 [ 0.57263033  0.36654613 -0.73330651]]


In [56]:
np.transpose(mat2)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [57]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Mean ,Mode,Median

In [64]:
from scipy import stats
speed=np.array([22,34,45,6,78,89,23,45,67,67,89,45,16])
m=np.mean(speed)
m1=np.median(speed)
print(m)
m2=stats.mode(speed)
print(m2)

48.15384615384615
ModeResult(mode=45, count=3)


## SD Varience

In [2]:
import numpy as np

In [3]:
speed=np.array([22,23,45,67,89,23,45,67,80,2,12,11])
print(speed.std())
print(speed.var())

28.10249099279279
789.75


## Percentile

In [8]:
speed1=np.array([22,23,45,67,89,23,45,67,80,2,12,11])
np.percentile(speed1,45)

23.0